# fly.toml app configuration file generated for emoji-niwa on 2026-05-16T20:13:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emoji-niwa'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  BIND_ADDR = '0.0.0.0:8080'
  DATA_PATH = '/data/state.json'

[[mounts]]
  source = 'niwa_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
